### PR TITLE
Fixed minor issues & Improved basic UI

### PR DESCRIPTION
**Pull request by yashksaini-coder**
## The changes this PR includes are:- 

This pull request sets up continuous deployment for the **ChatToAll** Flask application using GitHub Actions and Heroku. The changes include:

- **Added `gunicorn` to `requirements.txt`:**
  - Facilitates running the Flask app in a production environment.
  
  ```python
  Flask==2.1.3
  Werkzeug==2.1.2
  gunicorn
  ```

- **Created a `Procfile`:**
  - Specifies the command Heroku should use to start the application.
  
  ```procfile
  web: gunicorn app:app
  ```

- **Updated `README.md`:**
  - Added deployment instructions and documented the setup process for continuous deployment.
  
  ```markdown
  ## Deployment

  The application is set up for continuous deployment using GitHub Actions and Heroku. Upon pushing changes to the `main` branch, the workflow will automatically deploy the latest version to Heroku.

  ### Steps:

  1. Ensure `HEROKU_API_KEY` is added to GitHub Secrets.
  2. Push changes to the `main` branch.
  3. The GitHub Actions workflow will handle the deployment process.
  ```

- **Updated `.gitignore`:**
  - Ensures that sensitive information and unnecessary files are not tracked by Git.
  
  ```gitignore
  # Python
  __pycache__/
  *.pyc
  *.pyo
  *.pyd
  env/
  venv/
  ```
### 2. Migration of Data Store Format from TXT to JSON

- **Changed Data Storage from TXT to JSON:**
  - **Updated `app.py`:** Modified the backend to handle JSON data storage instead of plain text files.
  
    ```python:app.py
    from flask import Flask, request, jsonify, send_from_directory
    import os
    import json

    app = Flask(__name__)

    CHATLOG_PATH = 'data/chatlog.json'

    @app.route('/')
    def index():
        return send_from_directory('public', 'index.html')

    @app.route('/chat', methods=['POST'])
    def add_message():
        message = request.form['message']
        if os.path.exists(CHATLOG_PATH):
            with open(CHATLOG_PATH, 'r') as file:
                chat_data = json.load(file)
        else:
            chat_data = []
        chat_data.append({"message": message})
        with open(CHATLOG_PATH, 'w') as file:
            json.dump(chat_data, file, indent=4)
        return jsonify(success=True)

    @app.route('/chatlog', methods=['GET'])
    def get_chatlog():
        if os.path.exists(CHATLOG_PATH):
            with open(CHATLOG_PATH, 'r') as file:
                chat_data = json.load(file)
        else:
            chat_data = []
        return jsonify(chat=[entry['message'] for entry in chat_data])

    if __name__ == '__main__':
        app.run(debug=True)
    ```

  - **Added `chatlog.json`:** Introduced a JSON file to store chat messages persistently.
  
    ```json:data/chatlog.json
    [
        {
            "message": "hi"
        },
        {
            "message": "how are you ?"
        },
        {
            "message": "hope you are doing good!"
        }
    ]
    ```

  - **Created `chat.py`:** Abstracted chat-related operations into a separate module for better maintainability.
  
    ```python:chat.py
    # src/chat.py

    import json
    import os

    CHATLOG_PATH = '../data/chatlog.json'

    def read_chat():
        if os.path.exists(CHATLOG_PATH):
            with open(CHATLOG_PATH, 'r') as file:
                chat_data = json.load(file)
        else:
            chat_data = []
        return chat_data

    def write_chat(message):
        chat_data = read_chat()
        chat_data.append({"message": message})
        with open(CHATLOG_PATH, 'w') as file:
            json.dump(chat_data, file, indent=4)
    ```
## Benefits

- **Automated Deployment:** Streamlines the deployment process, reducing manual intervention and potential errors.
- **Scalability:** Utilizing `gunicorn` allows the application to handle multiple requests efficiently in a production environment.
- **Maintainability:** Clear separation of development and production configurations enhances the project's maintainability.

## Next Steps

- **Configure Environment Variables on Heroku:**
  - Set up necessary environment variables in Heroku's dashboard under **Settings > Config Vars**.
  
- **Monitor Deployment:**
  - Ensure that the GitHub Actions workflow runs successfully and the application is accessible post-deployment.

### CODE REVIEW

**Review by neovim-dev — COMMENTED** [review]
i am just here to say that the PR description is really good. Even if @yashksaini-coder used ChatGPT or Claude, the changes looks good. And the UI design is better than the previous one. 

@M-Aadhi I would like to contribute to this repo. With @yashksaini-coder if possible, can you assign the issue to me also ?

**Comment by M-Aadhi** [comment]
this pr allso have the same issue and in this project when try to fix the permission issue the buttons won't work cause of js code 

so I think we can make this in fully flask without js 
r the file transmission in third party host

**Comment by M-Aadhi** [comment]
@SamarAanand if u want a collab request let me know we can work together

**Comment by M-Aadhi** [comment]
@yashksaini-coder you gave the nice idea to use a JSON file instead of a Txt file 
but this project's main moto was to create a global free chat with the Txt file as database

**Comment by yashksaini-coder** [comment]
Thx for pointing ☝️ that @M-Aadhi 
I initially thought of using timestamp based json with relative text message. How ever the original requirements did not state any specific file format.

Also @SamarAanand requested to be assigned on this issue. I have no problems with that. Assign this issue to me & @SamarAanand 

After co-authoring commits please merge this PR.

Do you have any ideal platform for the deployment?

**Comment by M-Aadhi** [comment]
@yashksaini-coder for now it is  fine i will give a collab req to u in that make branch called json-in that branch u can pr the json data base plan so ur work won't waste

**Comment by yashksaini-coder** [comment]
@M-Aadhi Can you provide the changes you desired. I will start working on them after merging the PR. Alongside @SamarAanand

**Comment by M-Aadhi** [comment]
@yashksaini-coder ok it was working in local host and test host in mars code but it only won't work in deployment stages 
u can help with the two things 
1.slove the problem with the deploy stage and a fully working free global chat with the database of a txt file
2.we get that successful we can work with the CSS

if u accept the collab make 2 branch one for ur json plan
and another one our projects

**Comment by M-Aadhi** [comment]
well i create a branch for ur json plan (for-json) branch now give me a pr to that branch

**Comment by neovim-dev** [comment]
Thanks a lot @yashksaini-coder I have no problem in co-authoring commits and contributing together with the assigned issues at hand.

@yashksaini-coder Please add me on the new issue as well.

**Comment by yashksaini-coder** [comment]
No problem drop me a message on my discord handle

**Pull request closed without merging**
